### ISSUE TITLE
need to update documentation

### ISSUE THREAD

**Issue by childers** [NAL-i5K/genomics-workspace#123]
The install guide has a mistake.

The line ```virtualenv py2.7```

Should read:
```virtualenv -p python2.7 py2.7```

**Comment by hsiaoyi0504** [comment]
Although I don't think it's not a mistake, I think we should update this, because it will be more clear.
`virtualenv` without `-p` option will make  a virtual environment using the python version that installs the `virtualenv`.

**Comment by childers** [comment]
I have run afoul of this issue and agree with both your points. Thanks!
