### ISSUE TITLE
Blast results footer

### ISSUE THREAD

**Issue by childers** [NAL-i5K/genomics-workspace#198]
I thought we fixed this to be a calculated value instead of static.

<img width="507" alt="screen shot 2018-08-08 at 2 06 51 pm" src="https://user-images.githubusercontent.com/421248/43855703-730302a2-9b14-11e8-86db-24009e9c3a99.png">

Line in question:
https://github.com/NAL-i5K/genomics-workspace/blob/98dae7352e4b3c61313545560381f5970b253a1d/blast/static/blast/scripts/blast-results.js#L1209

**Comment by hsiaoyi0504** [comment]
@childers I think you mean this https://github.com/NAL-i5K/genomics-workspace/commit/200d08f4a8d65de29d0e9a899470a858dd825d83.

We can solve this in similar mechanism as well, though.
