### ISSUE TITLE
Remove duplicate requirements.txt

### ISSUE THREAD

**Issue by hsiaoyi0504** [NAL-i5K/genomics-workspace#23]
There are two files recording python dependencies, `requirements.txt` and `requirements_new.txt`. It seems that  `requirements_new.txt` was accidentally added one year ago. It should be removed because it may cause some confusion. It's a minor change, but I think it can be totally removed from git history.

**Comment by childers** [comment]
Also, can you check that the requirements.txt is up to date and complete?  The list of requirements in the readthedocs should also match the requirements.txt.

**Comment by hsiaoyi0504** [comment]
@childers I used the dependencies included in `requirements.txt` when I set up the environment on my mac, so I think it's up-to-date and complete.

@ifishlin Can you confirm that the content of `requirements.txt` is up-to-date and complete again? I afraid that there are some packages doesn't specify in that file and I haven't used the functionalities related to them, so I won't find issues about that.

**Comment by childers** [comment]
This should be completed with pull request 30.  Closing

**Comment by hsiaoyi0504** [comment]
Sorry, @childers I think we didn't remove the `requirements_new.txt`

**Comment by childers** [comment]
The two files do differ slightly.  

@ifishlin @hsiaoyi0504 
Can you verify that the information in requirements-new.txt is not needed?

**Comment by hsiaoyi0504** [comment]
@childers @ifishlin 

The screenshot of `vimdiff` of these two files is here. 
![screen shot 2017-09-26 at 1 35 02 am](https://user-images.githubusercontent.com/10943928/30822362-0c60e832-a25b-11e7-9671-4aab851d8083.png)

The left side is for `requirement.txt` and the right side is for `requirements-new.txt`
I do use the dependency specified in `requirement.txt` to install my environment.
I think I can test if `celery 3.1.23` works, but I  am not familiar with how `djangorestframework` and `django-suit`work on our project. Do you have any idea about them? @ifishlin

**Comment by hsiaoyi0504** [comment]
@ifishlin tell me that he thinks `djangorestframework` and `django-suit` are both need in our project and they should work even for newer version. I will create a PR based on this.

**Comment by childers** [comment]
@hsiaoyi0504 Removed the extra requirements-new.txt, and closing
