### ISSUE TITLE
remove some useless configuration in settings.py

### ISSUE THREAD

**Issue by childers** [NAL-i5K/genomics-workspace#245]
@deming7h777 commented on [Thu Oct 11 2018](https://github.com/NAL-i5K/general_issues/issues/1)

There are some file have been removed but the configuration is still in settings.py.(ex. jquery-ui.js,...)
It may confuse someone who want to figure out the whole genomics-workspace.

---

@hsiaoyi0504 commented on [Fri Oct 12 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429266760)

@deming7h777 Can you elaborate a little bit ? It seems to me that `jquery-ui.js` is still useful.

---

@deming7h777 commented on [Fri Oct 12 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429343230)

I can't find the jquery-ui.js in blast/script directory and even all of the repo, can you give me some suggestion

---

@hsiaoyi0504 commented on [Fri Oct 12 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429369142)

It's because it's installed by webpack: https://github.com/NAL-i5K/genomics-workspace/blob/84ec7d6901227dfe8dce8babf863eef31cc5c09c/webpack.config.js#L57.

---

@deming7h777 commented on [Sat Oct 13 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429577251)

I have seen that, i mean i don't find any script or html import jquery-ui.js 

---

@hsiaoyi0504 commented on [Sat Oct 13 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429581226)

It's imported by [django-pipeline](https://django-pipeline.readthedocs.io/en/latest/?badge=latest) through
https://github.com/NAL-i5K/genomics-workspace/blob/84ec7d6901227dfe8dce8babf863eef31cc5c09c/blast/templates/blast/results.html#L98
, and in **blast_results.js**, the jquery-ui widget is called by some syntax like this: 
https://github.com/NAL-i5K/genomics-workspace/blob/84ec7d6901227dfe8dce8babf863eef31cc5c09c/blast/static/blast/scripts/blast-results.js#L548.

---

@hsiaoyi0504 commented on [Sat Oct 13 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429585581)

BTW, this perhaps is a good alternative of **django-pipeline**: https://django-compressor.readthedocs.io/en/latest/. One important feature attracts me is that 

> **JS/CSS belong in the templates**
Every static combiner for Django I’ve seen makes you configure your static files in your settings.py. While that works, it doesn’t make sense. Static files are for display. And it’s not even an option if your settings are in completely different repositories and use different deploy processes from the templates that depend on them. - django-compressor

---

@deming7h777 commented on [Mon Oct 15 2018](https://github.com/NAL-i5K/general_issues/issues/1#issuecomment-429852276)

thanks for reminding !

**Comment by hsiaoyi0504** [comment]
This should be
