### ISSUE TITLE
Include DAP government code into app-layout.js

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/genomics-workspace#246]
Currently, we include the DAP government code into our template

https://github.com/NAL-i5K/NAL-genomics-workspace/blob/5b6e56257be1094e0c70ce8c2e45cda41db26bef/app/templates/app/layout.html#L19

but based on https://github.com/digital-analytics-program/gov-wide-code/issues/65, we can now track this dependency by package.json and include it into app-layout.js generated by django-pipeline

Related links:

https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm
https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

**Comment by hsiaoyi0504** [comment]
This issue should be opened in [NAL-genomics-workspace](https://github.com/NAL-i5K/NAL-genomics-workspace). Not this one.

**Comment by deming7h777** [comment]
Issue moved to [NAL-i5K/NAL-genomics-workspace #13](https://github.com/NAL-i5K/NAL-genomics-workspace/issues/13) via [**ZenHub**](https://www.zenhub.com/)
