### ISSUE TITLE
[BLAST query page] Adding searchBar

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/genomics-workspace#271]
As the number of organisms growing, I believe that searchBar is better than a scrollBar in the aspect of working efficiency for BLAST user

- Link:
https://i5k.nal.usda.gov/webapp/blast/

- The result might look like this:
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/4cb7bf49-ada7-4969-ae2f-1e3687292b14)

**Comment by r06942072** [comment]
Related issue: #243

**Comment by r06942072** [comment]
Goal: find a way to simplyify the connection between code and UI interface (ex. WIX)

Ref: 
- Tricks for writing maintainable Front-end code
https://medium.com/@chenzhe142/tricks-for-writing-maintainable-front-end-code-c9a67daade4f

**Comment by r06942072** [comment]
Technical Tool:  
React + Webpack + Babel.
Usage:   
Webpack: bundle js file, project management
Babel: Compiler tackling syntax difference btw version

**Comment by hsiaoyi0504** [comment]
I totally agree that  search bar is useful. However, I think we still need to keep the scroll bar to let user browse all the organisms available.

**Comment by r06942072** [comment]
@hsiaoyi0504 True, I agree with you. I change the issue name as "Adding searchBar to BLAST query page". Let's keep the scrollBar
