### ISSUE TITLE
Final step to Integrate the adding organism functionality to CWL and fix CI issue

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/genomics-workspace#279]
1. integrate the duplicate module from addblast and addhmmer
2. fix django function 
3. fix trailing space issue
4. consider to move CWL project under django app

**Comment by mpoelchau** [comment]
@deming7h777 I'd rather just be able to run CWL to add the organism to python if that's possible. We should discuss if that's too complicated.

**Comment by deming7h777** [comment]
> @deming7h777 I'd rather just be able to run CWL to add the organism to python if that's possible. We should discuss if that's too complicated.

Chun-hung and I have a discussion about it in last two days, we can have further detailed discussion in individual meeting

**Comment by deming7h777** [comment]
Now I'm working on cognitive complexity issue and almost finish it.
I also encounter another issue about the similar coding block within makeblastdb.py and populatesequence.py.
