### ISSUE TITLE
vulnerabilities of django 1.11.20 and update blastdbcmd argument

### ISSUE THREAD

**Issue by deming7h777** [NAL-i5K/genomics-workspace#292]
travis ci error : https://travis-ci.org/NAL-i5K/genomics-workspace/jobs/562726464

**Comment by hsiaoyi0504** [comment]
Was updated to 1.11.20 https://github.com/NAL-i5K/genomics-workspace/pull/286.

**Comment by hsiaoyi0504** [comment]
I think this can be closed. @childers

**Comment by childers** [comment]
Thanks!
