### ISSUE TITLE
Best practice for migrations of Django project

### ISSUE THREAD

**Issue by hsiaoyi0504** [NAL-i5K/genomics-workspace#41]
As described in this stackoverflow question:
https://stackoverflow.com/questions/33784362/django-migrations-best-practice

The same question comes to my mind when I first started working on this project.
During the configuration step, we need to `makemigrations` and `migrate`, which is different from my previous experience of other django project (although I didn't work on model part of MTV framework). Maybe we should consider to follow this kind of best practice?

**Comment by childers** [comment]
I like the idea of creating the migrations files locally then committing them to version control.  In the case of a developer forgetting to commit their migrations, how difficult would it be for another developer to catch the repository up?

**Comment by hsiaoyi0504** [comment]
Sorry, Chris. I am not sure what you mean. Do you want to ask me how should we handle that case or just want to express it's a good idea?

**Comment by childers** [comment]
Whoops for not responding sooner.  I think this looks like a good idea.

**Comment by hsiaoyi0504** [comment]
It looks like we have already adopting this :)
